### ISSUE TITLE
more modular

### ISSUE THREAD

**Issue by calvinmetcalf** [crypto-browserify/crypto-browserify#105]
so somebody can just require like crypto-hmac or crypto-sign, Not sure the best way but hashes and random numbers are the ones that tend to be needed in the other ones so breaking those out might be a first step

**Comment by jprichardson** [comment]
I've been a big proponent of this for awhile. It makes development and maintenance for each component much simpler. Awhile back, I setup https://github.com/crypto-browserify with the goal of doing this. I'm willing to give it to anyone that wants to start. I've brought the idea up to @dominictarr before, but as I recall he wasn't too keen on the idea - fair enough, as it's his project. If any of you want the group, I'll add as admin / owner.

(I realize this can be done without a Github group and that's totally cool too, just wanted to offer the group if anyone was interested)

**Comment by calvinmetcalf** [comment]
the tricky thing to get right will be dependency management, I had oh so much fun upgrading all the various packages that depend on bn.js and would like to avoid having to manually upgrade everything when say hashes upgrade @indutny uses optional dependencies for his packages that all require bn.js and that might be a fit for us.

org sounds like a good idea, I've been meaning to bring that up as well if for no other reason than to get all the packages under one roof, adding me @dcousens and @dominictarr would be a good start there.

**Comment by indutny** [comment]
Makes sense to me. Why calling it `crypto-browserify`, though? `crypto.js` would be much more generic :)

**Comment by indutny** [comment]
`cryptojs` appears to be occupied.

**Comment by jprichardson** [comment]
> Makes sense to me. Why calling it crypto-browserify, though? crypto.js would be much more generic :)

That becomes a scope issue then. Which would be fun to discuss as well :) But, it seems to make sense that this library focuses solely on providing a node compatible API for the browser via Browserify. Building `crypto.js` would introduce a whole new set of issues. As it stands now, at least our scope is more limited and this is a good thing IMHO.

**Comment by jprichardson** [comment]
`crypto.js` could then be built on top of `crypto-browserify`?

**Comment by indutny** [comment]
@jprichardson oh, perhaps, I just got the whole thing a bit wrong. Are you proposing to move `bn.js` and other stuff from me to the github org?

**Comment by dcousens** [comment]
@indutny I think the proposal was to initially move all the crypto-browserify components to a organization.    Eventually, I think a JS crypto organization would also be beneficial, but would require some discussion of scope for sure.

**Comment by jprichardson** [comment]
> @jprichardson oh, perhaps, I just got the whole thing a bit wrong. Are you proposing to move bn.js and other stuff from me to the github org?

Oh, no. Haha. I was proposing moving / breaking up modules directly related to `crypto-browserify`. `bn.js` seems to me that it'd have much wider application and usage outside of `crypto-browserify`. The same could be said for `elliptic`. But things that would be applicable would be code that is written solely to provide browser compatibility for this library - most notably, the direct dependencies that this library has.

**Comment by jprichardson** [comment]
> @indutny I think the proposal was to initially move all the crypto-browserify components to a organization.

Yup :)

**Comment by jprichardson** [comment]
I'll add everyone to the organization as owner (full-control), but out of respect, I'd like to get @dominictarr's opinion first. https://github.com/dominictarr/crypto-browserify could stay the same, but the dependencies moved over. Then, over time, parts of `crypto-browserify` could be broken up into other modules and moved into the organization.

**Comment by calvinmetcalf** [comment]
@jprichardson as a first step just thinking of the other modules that I, @dominictarr and @dcousens have related to crypto, plus a hash/hmac and a random one

@indutny was just using bn.js as an example though part of my thinking is to make it easy for you (or anyone) to use the same hash and random number libraries as we do.  My origional train of thought started with 'elliptic should use the same random number generator and hmac as us' followed by me realizing the library wasn't set up in a way that made that possible.

**Comment by calvinmetcalf** [comment]
off the tope of my head the current dependency graph is something like

- hashes
- hmacs
    - hashes (just md5)
- ciphers
    - hashes
- pbkdf
    - hmacs
- sign
    - ciphers
    - hashes
    - hmacs
    - elliptic
    - rsa
    - parse-asn1
- publicEncrypt
    - random
    - hashes
    - rsa
    - parse-asn1
- rsa
    - random
- diffie-hellman
    - random
- ecdh
    - elliptic
- elliptic
    - random
    - hmac

**Comment by dominictarr** [comment]
@jprichardson I have changed my mind about the org now.

There are now alot more people who are heavily contributing to crypto-browserify and that I trust as much as - if not more than - myself to write and audit quality code.

Lets do this!

**Comment by jprichardson** [comment]
Done. Invites sent. 

If wanted, I'll bring over https://github.com/cryptocoinjs/ripemd160 since it's a dep. But, I'll defer to you guys and your judgement on how to best manage and maintain things.

I'm excited for this!

**Comment by dcousens** [comment]
Happy to move `pbkdf-compat` also.

**Comment by dominictarr** [comment]
we should probably move all the core deps in, i'd say that bn.js can live outside, but `pbkdf-compat` feels like it should be part of `crypto-browserify`

**Comment by dominictarr** [comment]
I moved crypto-browserify, sha.js, and hash-test-vectors to the crypto-browserify org

**Comment by calvinmetcalf** [comment]
bringing in ripemd160 sounds like a good plan

**Comment by jprichardson** [comment]
I moved over `ripemd160` - added more test vectors, updated the readme, and changed version from `0.2.1` to `1.0.0` given that it's been pretty stable for some time now.

**Comment by calvinmetcalf** [comment]
ok see #109 which does this for hashes

**Comment by dcousens** [comment]
This has entirely been realized.  Closed.
