### ISSUE TITLE
what node version are we targeting?

### ISSUE THREAD

**Issue by dominictarr** [crypto-browserify/crypto-browserify#118]
@dcousens mentions here:
https://github.com/crypto-browserify/pbkdf2-compat/pull/4#issuecomment-71147828

I don't think we have a formal answer that we have commited to, but we have merged PRs that give 0.11 compat, so I guess the answer is 0.11

Can we improve this answer?

**Comment by dcousens** [comment]
Is this still the case?

**Comment by calvinmetcalf** [comment]
No we support io as well

**Comment by dcousens** [comment]
The answer is the lowest LTS version,  as that as what we keep up with in the sub-modules.

4.0.0 now.
