### ISSUE TITLE
Standard

### ISSUE THREAD

**Issue by dcousens** [crypto-browserify/crypto-browserify#120]
Thoughts on using https://github.com/feross/standard across all the modules?
It'll take a bit of transitional work to get some of them up to scratch, but it will enforce a standard (ha) that is tested.

I've [added](https://github.com/crypto-browserify/pbkdf2-compat/blob/master/.travis.yml#L10) [it](https://github.com/crypto-browserify/pbkdf2-compat/blob/master/package.json#L16) to pbkdf2-compat for now.

**Comment by jprichardson** [comment]
I love the idea of this module, but I feel that @feross has been a bit overzealous about its settings and it's more than just style. It does a lot that it shouldn't do IMHO. See:

- https://github.com/feross/standard/issues/9 
- https://github.com/feross/standard/commit/91e8a4183b513dd4f276f7095f7d46c6032c7dfe

**Comment by feross** [comment]
@jprichardson Thanks for the feedback. I agree with you and just removed the `undef` rule. :)

**Comment by feross** [comment]
@dcousens You might take a look at @maxogden's experimental [`standard-format`](https://github.com/maxogden/standard-format) tool for helping with that transitional work.
