### ISSUE TITLE
RS256 verification failure using json web tokens

### ISSUE THREAD

**Issue by bnolan** [crypto-browserify/crypto-browserify#130]
This issue:

https://github.com/auth0/node-jsonwebtoken/issues/91

I think is a browserify issue, it passes in node, but fails in browserify. I've tried two different JWT implementations and get the same results.

**Comment by calvinmetcalf** [comment]
the word is done over in browserify-sign so I opened crypto-browserify/browserify-sign#13 let me see if I can extract a test

**Comment by calvinmetcalf** [comment]
ok reproduced it reliably

**Comment by calvinmetcalf** [comment]
I believe this is fixed upstream
