### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by dcousens** [crypto-browserify/crypto-browserify#133]
Seems to be a problem with BN.js

Ping @calvinmetcalf ,  are you getting the same results?  It is failing in miller-rabin.

**Comment by calvinmetcalf** [comment]
ah bn.js had a major version bump, miller-rabin upgraded but was only minor bumped

**Comment by calvinmetcalf** [comment]
fixed make sure to clear your cache

**Comment by dcousens** [comment]
Thanks! :)
