### ISSUE TITLE
ripemd160 is not supported

### ISSUE THREAD

**Issue by braydonf** [crypto-browserify/crypto-browserify#135]
Browser implementation available here:
https://github.com/indutny/hash.js

**Comment by dcousens** [comment]
`ripemd160` is supported?

**Comment by jprichardson** [comment]
@braydonf https://github.com/crypto-browserify/ripemd160

Presumably you're using `ripemd160` as opposed to `rmd160` (https://github.com/crypto-browserify/crypto-browserify/blob/5086f438de6cb318203d180817cf326a2a143156/index.js#L7) ?

**Comment by braydonf** [comment]
Nice! Yep, that was it. Using `rmd160` works.

This error message was appearing with `ripemd160`, "Error: ripemd160 is not supported (we accept pull requests)"

**Comment by calvinmetcalf** [comment]
we should probably put an alias in [here](https://github.com/crypto-browserify/createHash/blob/dcc25f9e0b66d07fbf76d13e2616ea4c34cbcc90/browser.js#L86)

**Comment by dcousens** [comment]
@calvinmetcalf why isn't that an object lookup anyway?

**Comment by calvinmetcalf** [comment]
probably should be, also probably should have toLowerCase() called on it

**Comment by DalderupMaurice** [comment]
For people who are still having this issue.
Update: node-libs-browser
(npm i node-libs-browser)
This package pulled in an old version of createHash within crypto-browserify.
