### ISSUE TITLE
DES support?

### ISSUE THREAD

**Issue by indutny** [crypto-browserify/crypto-browserify#136]
I just needed it myself, and did it in:

https://github.com/indutny/des.js

Perhaps it could be used in `crypto-browserify` too?

Currently supported ciphers:

* `des-ecb`
* `des-cbc`
* `des-ede3-ecb`
* `des-ede3-cbc`

**Comment by dcousens** [comment]
@indutny,  is it available in node?

**Comment by indutny** [comment]
Mmm.. of course, all of them are available via `crypto.createCipher`/`crypto.createCipheriv` (and deciphers too)

**Comment by calvinmetcalf** [comment]
no reason not to include it, though looking at the library we'd need to make them sub classes of streams.  You probably don't want that in your library because it will slow things down, but we could create a wrapper library to pull in DES.

**Comment by indutny** [comment]
Cool, thank you!

**Comment by calvinmetcalf** [comment]
ok step 1 i've extracted the cipher-base out into it's own module, I think next I need:
- to extract EVP_BytesToKey into it's own module
- make a des-browserify package that provides createCipherIV stuff
- make a cipher package that consumes both des and aes and move the stuff for createCipher there

**Comment by dcousens** [comment]
That sounds like a good roadmap @calvinmetcalf :+1:

**Comment by indutny** [comment]
Hooray!

**Comment by calvinmetcalf** [comment]
#137

**Comment by dcousens** [comment]
Added
