### ISSUE TITLE
rng.js Buffer use causes PhantomJS failure

### ISSUE THREAD

**Issue by bvaughn** [crypto-browserify/crypto-browserify#143]
I recently began seeing the following error while running tests in a React application:

```
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  TYPE_MISMATCH_ERR: DOM Exception 17: The type of an object was incompatible with the expected type of the parameter associated to the object.
  at /path/to/my/test.js <- webpack:///~/node-libs-browser/~/crypto-browserify/rng.js:20:0
```

After some experimenting, I was able to resolve this error by updating `rng.js` to replace this...

``` javascript
var bytes = new Buffer(size); //in browserify, this is an extended Uint8Array
```

...with this...

``` javascript
var bytes = new Uint8Array(size); //in browserify, this is an extended Uint8Array
```

I don't understand (based on the comment) why `Buffer` was used in the first place instead of just `Uint8Array` but it seems to cause problems for PhantomJS. Is this something that could be changed?

**Comment by calvinmetcalf** [comment]
see crypto-browserify/randombytes#3

**Comment by calvinmetcalf** [comment]
the tl;dr is that buffer is a modified u8intarray but there is a bug in phantomjs that incorrectly rejects it

**Comment by bvaughn** [comment]
Hotness. Thanks for the prompt response, Calvin.

**Comment by coolaj86** [comment]
I also updated node-uuid so that it will test the rng function that it creates before assuming that it works. https://github.com/broofa/node-uuid/commit/7bb3cb6218dd60fa7334c10fe8d3a8a481ba6154
