### ISSUE TITLE
privateEncrypt/publicDecrypt not implemented

### ISSUE THREAD

**Issue by arturojain** [crypto-browserify/crypto-browserify#146]

**Comment by calvinmetcalf** [comment]
this is not correct unless you are using a very old version

**Comment by arturojain** [comment]
Not show in README, it only shows implementation for publicEncrypt/privateDecrypt

**Comment by arturojain** [comment]
I see it is implemented, you should add it to the README

**Comment by calvinmetcalf** [comment]
You know, you could add it to the readme with a pull request you know.   If
not one of us can at some point.

**Comment by arturojain** [comment]
Ok, this is my first time contributing to a project. So it's kind of intimidating.

**Comment by calvinmetcalf** [comment]
and you did it perfectly
