### ISSUE TITLE
waffle.io

### ISSUE THREAD

**Issue by fanatid** [crypto-browserify/crypto-browserify#152]
Since @crypto-browserify has many small modules, it would be great see all issues/pr in one place. [waffle.io](https://waffle.io/) looks good things for this.

@dcousens @jprichardson I think we also should activate waffle for @cryptocoinjs and @bitcoinjs

**Comment by dcousens** [comment]
I might try it out internally on a few projects before I commit to it on @bitcoinjs

**Comment by dcousens** [comment]
https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Acrypto-browserify+
