### ISSUE TITLE
Sha512 listed as implemented, but throws error

### ISSUE THREAD

**Issue by swimmadude66** [crypto-browserify/crypto-browserify#153]
```
EXCEPTION: Error: algorithm: sha512 is not yet supported
we accept pull requests
http://github.com/dominictarr/crypto-browserify
```

**Comment by dcousens** [comment]
It is certainly supported.  What versions are you running?  `node`, `crypto-browserify`, etc

**Comment by swimmadude66** [comment]
```
node --version
v6.0.0
```


 I'm unsure how to check crypto-browserify version, since it is pulled down by gulp-browserify at build time.

**Comment by dcousens** [comment]
https://github.com/deepak1556/gulp-browserify

> NOTE: THIS PLUGIN IS NO LONGER MAINTAINED , checkout the recipes by gulp team for reference on using browserify with gulp.

Perhaps just try browserifying an example yourself?  If that still doesn't work,  I'd be interested to find out more about why..

**Comment by swimmadude66** [comment]
right on the money. I swapped out gulp-browserify for one of the browserify recipes and Bob's your uncle! Thanks for the help!

**Comment by adridadou** [comment]
Hi, sorry I feel stupid but I don't get what you have done. I have the same issue and I don't see how I can rid of this error message. Can you tell me what you mean by "swapped out gulp-browserify for on of the browserify recipes" ?  Thx!

**Comment by dcousens** [comment]
@adridadou just use `browserify` [directly](https://github.com/substack/node-browserify).
If you still need `gulp`,  you could make your own transform, or update that plugin and submit a pull request.
The choice is yours,  but ultimately `bitcoinjs-lib` and `browserify` work fine.

**Comment by adridadou** [comment]
I see. So I need to use browserify directly instead of using gulp-browserify. I'll try that and hopefully everything will work. Thank you !
