### ISSUE TITLE
node 5, 6 on travis

### ISSUE THREAD

**Issue by dcousens** [crypto-browserify/crypto-browserify#155]
What's the plan @dominictarr?
Do we double up all the current tests there for node 5 and 6 or do we wait out?

Or is it not relevant? Not sure

**Comment by dominictarr** [comment]
hmm... okay what about, migrate crypto-browserify to have the node@6 behavior by always never passing strings to the built in crypto - convert to a buffer with utf8...

maybe could have a `require('crypto-browserify/legacy')` mode,
OR if a user really needs the old thing they should explicitly create a buffer and use binary encoding.
(which is what we did in secure-scuttlebutt, but that is temporary until we get the other stuff in place to replace that)

This is gonna be a massive pain no matter what, but this seems like the most sane approach?

**Comment by dcousens** [comment]
> hmm... okay what about, migrate crypto-browserify to have the node@6 behavior by always never passing strings to the built in crypto - convert to a buffer with utf8...

Sound safe.
Then the only real question is do we maintain a `"binary"` default?

I think a `/legacy` would just change that default,  and I think would be *good* enough...  just make sure its all in some release notes.

**Comment by dcousens** [comment]
> This is gonna be a massive pain no matter what, but this seems like the most sane approach?

Release a minor version update now where if "binary" was given or defaulted,  then it warns very loudly.

Then, deprecate/remove `"binary"` in a major,  throwing a loud exception on being passed.
At that point,  `"binary"` can only be achieved manually.

**Comment by dcousens** [comment]
It seems we just... "pushed" through by having it default to different codecs based on `process.version`. See https://github.com/crypto-browserify/pbkdf2/issues/34
