### ISSUE TITLE
createhMac not implemented yet error

### ISSUE THREAD

**Issue by danifantom** [crypto-browserify/crypto-browserify#157]
![image](https://cloud.githubusercontent.com/assets/16234163/21084283/596b7116-bfe8-11e6-9ec7-5861f423e1b2.png)

In the repo says that it is

**Comment by jprichardson** [comment]
What version of Browserify are you using? Presumably a very old one? https://github.com/crypto-browserify/crypto-browserify/blob/eea13e59d89978d0d8fb5b237bcead3dfd9add5e/package.json#L25

**Comment by danifantom** [comment]
I downloaded the latest one 3.11...
Maybe I don't know exactly how to use it. I've just copied the bundle.js from the example folder. I know that's not the correct way to do it at all. So how must I do this?

**Comment by jprichardson** [comment]
1. Install browserify `npm i -g browserify` (I'm assuming you have Node.js / npm installed)

2. I'd then recommend that you read this for reference: https://github.com/substack/browserify-handbook or https://github.com/substack/node-browserify

Hope this helps.
