### ISSUE TITLE
rng.js causes _crypto not defined error with webpack

### ISSUE THREAD

**Issue by csquires** [crypto-browserify/crypto-browserify#158]
I don't know how rng.js gets into the crypto-browserify folder, but line 3 reads `_crypto = (`, causing an error in webpack. Placing `var` at the beginning of the line fixes the error.

**Comment by calvinmetcalf** [comment]
I believe you are using a very old version of this

**Comment by csquires** [comment]
I did `npm view crypto-browserify version` and I see 3.11.0. Somebody else is having this issue as well:
http://stackoverflow.com/questions/41156123/crypto-is-not-defined/41183485#41183485

**Comment by calvinmetcalf** [comment]
3.11.0 doesn't actully have _rng.js, that's been gone since 3.9.8, I think something has required a really old versoin

**Comment by edisonator** [comment]
I've had the same problem, and found the reason.

As you use webpack 1.x, the `node-libs-browser@7.0` with `crypto-browserify@3.3.0` (maybe earlier) will be installed at the same time.

So, if you just `require('crypto')` directly, webpack will use the `@3.3.0`, which has the `rng.js`, and not the newest version you installed by yourself.

![image](https://cloud.githubusercontent.com/assets/7287198/21517670/f788b102-cd1b-11e6-8b97-03a6f3fb44ce.png)

The solution I tried is just `npm install node-libs-browser --save`, and npm will update it in webpack, and @3.11.0 will be found.
