### ISSUE TITLE
crypto.constants are missing

### ISSUE THREAD

**Issue by christiaan** [crypto-browserify/crypto-browserify#159]
According to https://nodejs.org/dist/latest-v6.x/docs/api/crypto.html#crypto_crypto_constants I should be able to use `crypto.constants.RSA_PKCS1_OAEP_PADDING` with `privateDecrypt`.

Instead of using the constant I used it's value (4) instead and it works fine.

Can I just copy the list of constants from the nodejs source and make a PR?

**Comment by calvinmetcalf** [comment]
we probably just want the one's under `Other OpenSSL Constants` but otherwise YES! pull requests accepted

**Comment by christiaan** [comment]
Pull request made See #160
