### ISSUE TITLE
Broken by browserify-sign@4.0.1

### ISSUE THREAD

**Issue by rmg** [crypto-browserify/crypto-browserify#161]
Not an issue with crypto-browserify itself, but posting here in case this is where people look.

Upstream issue is crypto-browserify/browserify-sign#34, where the recent release of 4.0.1 removed `browserify-sign/algos` which has been used by crypto-browserify for a while.

**Comment by rmg** [comment]
Fixed by [`browserify-sign@4.0.2`](https://github.com/crypto-browserify/browserify-sign/releases/tag/v4.0.2).

I'll leave this open for a short while longer in case anyone catches a cached broken version and comes looking.

**Comment by calvinmetcalf** [comment]
actually fixed by 4.0.3 but yes should be good
