### ISSUE TITLE
"SCRIPT0: secure random number generation not supported by this browser use chrome, FireFox or Internet Explorer 11"

### ISSUE THREAD

**Issue by omryr** [crypto-browserify/crypto-browserify#165]
Hi, I am using webpack and its loading crypto-browserify 3.11,
when using IE explorer or safari on mobile it throws the error in the title.

did this happen to anyone else? and if yes, what was the fix?

**Comment by calvinmetcalf** [comment]
if you could answer the questions I asked over at crypto-browserify/randombytes#6 that would go a long way towards figuring this out

**Comment by dcousens** [comment]
Closing in favour of https://github.com/crypto-browserify/randombytes/issues/6
