### ISSUE TITLE
test failures depending on openssl compilation flags

### ISSUE THREAD

**Issue by kapouer** [crypto-browserify/crypto-browserify#175]
Algorithms available at runtime depend on how openssl (which could be a shared lib) has been configured.
Test such as https://github.com/crypto-browserify/crypto-browserify/blob/9730d317e2141099b8e56d2afbaf806eb616e0a3/test/sign.js#L34
should not assume all algorithms are available.
The test could either catch the exception (createSign throws with "Unknown message digest") or check `crypto.getCiphers()`.

See also https://github.com/crypto-browserify/browserify-sign/issues/37

**Comment by kapouer** [comment]
Here's a log, and i'll PR a workaround:

```
# ec with sha1
# js sign and verify
ok 95 validates
# node sign and verify
crypto.js:291
  this._handle.init(algorithm);
               ^

Error: Unknown message digest
    at new Sign (crypto.js:291:16)
    at Object.Sign (crypto.js:289:12)
    at Test.<anonymous> (/<<PKGBUILDDIR>>/test/sign.js:34:31)
```

**Comment by calvinmetcalf** [comment]
in this repo is the issue just that ecdsa with sha1 isn't supported or the specific curve ?

**Comment by kapouer** [comment]
Gimme a minute :)

**Comment by kapouer** [comment]
List of failures:
```
# node sign and verify
skipping unsupported scheme ecdsa-with-SHA1
# node sign and js verify
skipping unsupported scheme ecdsa-with-SHA1
# js sign and node verify
skipping unsupported scheme ecdsa-with-SHA1

```

**Comment by calvinmetcalf** [comment]
ok so it looks like it's just sha1 which is the issue here so if we just change [this](https://github.com/crypto-browserify/crypto-browserify/blob/9730d317e2141099b8e56d2afbaf806eb616e0a3/test/sign.js#L59) line to be `sha256` that should fix it

**Comment by kapouer** [comment]
Do you mean replace `ecdsa-with-sha1` by `sha256`?

**Comment by kapouer** [comment]
It works now.

**Comment by kapouer** [comment]
Note that it's more something about default security setup than about debian in itself.

**Comment by calvinmetcalf** [comment]
#176 works or this repo always worked ?

**Comment by kapouer** [comment]
#176 works. It was failing before.

**Comment by calvinmetcalf** [comment]
ok great
