### ISSUE TITLE
how to use createVerify (rsa, ecdsa)?

### ISSUE THREAD

**Issue by oldturkey** [crypto-browserify/crypto-browserify#177]
how to use this npm to createVerify rsa sign  for browserify ?
i found so mach,but can't get a example,   can you give me an example?

thanks guy!

**Comment by calvinmetcalf** [comment]
[just like in node](https://nodejs.org/api/crypto.html#crypto_crypto_createverify_algorithm_options)

**Comment by oldturkey** [comment]
const rsa_sha1_verify = function (k, m, s) {
      console.log("key:" + k);
      console.log("msg:" + m);
      console.log("sig:" + s);
      var mb = new Buffer(m, 'base64');
      var sb = new Buffer(s, 'base64');
      var s = crypto.createVerify('RSA-SHA1');
      s.update(mb);
      return s.verify(k, sb, 'base64');
};
console.log(rsa_sha1_verify(publicKey,data,signature));

i use it like this,but gei wrong message at :decrypted = new Buffer(match2[2].replace(/\r?\n/g, ''), 'base64')
