### ISSUE TITLE
Please add a tag for version 3.12.0

### ISSUE THREAD

**Issue by sschuberth** [crypto-browserify/crypto-browserify#178]
Currently, commit https://github.com/crypto-browserify/crypto-browserify/commit/5ffcb3c1c8c0715cb0d75ce012103e70cc625e8c for version 3.12.0 (as per `gitHead` the [registry](https://registry.npmjs.org/crypto-browserify)) is not on any fetchable ref. Please fix that by actually adding a Git tag pointing to https://github.com/crypto-browserify/crypto-browserify/commit/5ffcb3c1c8c0715cb0d75ce012103e70cc625e8c.

**Comment by calvinmetcalf** [comment]
done though for various reasons it's dcbe3bf731a438a802bf0936108a8abe055356ad

**Comment by sschuberth** [comment]
Thanks!
