### ISSUE TITLE
AWS JS SDK Fails with this dependency

### ISSUE THREAD

**Issue by Ch3ck** [crypto-browserify/crypto-browserify#180]
Some how the AWS JS SDK uses this package and in `rng.js` which I don't seem to find anymore in this source code creates an undefined variable  for `_global` which we fixed with this:
`var_global = this || window || {};`

You can find more issues related to this package here:
1. https://github.com/aws/aws-sdk-js/issues/1512
2. https://github.com/aws/aws-sdk-js/issues/1566

Where the full source for this package so I can write a patch for this fix?

**Comment by calvinmetcalf** [comment]
the error is in [randombytes](https://github.com/crypto-browserify/randombytes) but the real issue is that this was written for browserify/webpack with the assumption that there will be a variable named 'global' and thus bundling this with certain webpack configurations will break that assumption

**Comment by dcousens** [comment]
@calvinmetcalf we could `|| window` it.  Though,  it does sound like a problem with their build process, not us.

**Comment by calvinmetcalf** [comment]
ok I just went and looked at the actual library, and we don't use the rng.js file anymore so this is almost certainly an issue with a really out of date version of this library

**Comment by Ch3ck** [comment]
Where can I find the latest version of the library, I think I'll need to create an issue with the AWS sdk people to update the libary.

**Comment by calvinmetcalf** [comment]
they have said in the issue that they don't rely on the this anymore so the
only reason you'd be getting it is an out of date version of aws

**Comment by Ch3ck** [comment]
that's weird because I just installed the latest version from `yarn` except it doesn't have the latest version. However, I just filed some issues with them to see if they can get this resolved.

**Comment by calvinmetcalf** [comment]
what are you using to bundle the library and have you tried removing your yarn.lock

**Comment by Ch3ck** [comment]
I'm using webpack and I've reinstalled all the packages, and the currently supported `crypto-browserify` version is `1.0.9`  seems like this needs to be updated. I don't really know the current version now.

**Comment by calvinmetcalf** [comment]
3.12.0

**Comment by Ch3ck** [comment]
I've added a PR to the amazon-identity package.
