### ISSUE TITLE
Module appeared and imported by itself

### ISSUE THREAD

**Issue by maliyshock** [crypto-browserify/crypto-browserify#189]
For some reason `import {createPrivateKey} from "crypto";` appeared in the file, which I worked with. I do not know how does it happen. I did not pull from repository or install any npm modules.
It's just appeared by itself... О_о

I am working with MacOs Siera 10.13.4 and I use PHP storm 2017.2.5

Do you have any idea why it happens?

**Comment by Jerska** [comment]
Wild guess: you are working with `vscode` or similarly "advanced" IDE and it tried to automatically import a function you were using in your file?

**Comment by maliyshock** [comment]
Yeah. Stupid thing. You are right. It was my IDE
