### ISSUE TITLE
Security vulnerability in browserify-sign

### ISSUE THREAD

**Issue by mikaelharsjo** [crypto-browserify/crypto-browserify#192]
The `4.0.0` version of `browserify-sign` depends on a version `elliptic` that has a vulnerability. You should update it too `4.2.1`.

**Comment by diracdeltas** [comment]
There is another vulnerability here: https://www.npmjs.com/advisories/1547 (fixed in 6.5.3)

**Comment by sarimarton** [comment]
Can we move this forward? It blocks me in an enterprise env, where snyk spots this issue.

**Comment by calvinmetcalf** [comment]
delete your package-lock or yarn-lock and reinstall, this project calls for `^4.0.0` which means `>= 4.0.0 && <5.0.0` so it should use the latest version of browserify-sign

**Comment by sarimarton** [comment]
Thanks, indeed it solved the problem. (I guess this issue can be closed then.)
