### ISSUE TITLE
better release process

### ISSUE THREAD

**Issue by dominictarr** [crypto-browserify/crypto-browserify#75]
I've done something dumb and published a broken release more than once.
Given the seriousness of crypto, this is not acceptable, and we need a better way.

I'm thinking something along the lines of all releases should be a pull request,
which are then validated and published by another contributor.
@calvinmetcalf, you have been putting most of the work into this recently,
I could add you as an npm owner, and then one of us prepares a release, but the other one publishes it.

Alternatively, I've just added a prepublish test that would have prevented 3.4.0 getting out.
https://github.com/dominictarr/crypto-browserify/commit/ce2593913cbd98f55bbfa480004cd2dfcebea232

Maybe this will be enough?

**Comment by dcousens** [comment]
This has been the case for a while now.  Closing.
